import {IIngredient, IngredientTypes} from "../models/Ingredients";

export const BUN1: IIngredient = {
    _id: "643d69a5c3f7b9001cfa093c",
    type: IngredientTypes.bun,
    name: "Краторная булка N-200i",
    proteins: 80,
    fat: 24,
    carbohydrates: 53,
    calories: 420,
    price: 1255,
    image: "https://code.s3.yandex.net/react/code/bun-02.png",
    image_large: "https://code.s3.yandex.net/react/code/bun-02-large.png",
};

export const BUN2: IIngredient = {
    _id: "643d69a5c3f7b9001cfa093d",
    type: IngredientTypes.bun,
    name: "Флюоресцентная булка R2-D3",
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    image: "https://code.s3.yandex.net/react/code/bun-01.png",
    image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
};

export const TEST_INGREDIENTS: IIngredient[] = [
    {
        _id: "643d69a5c3f7b9001cfa0941",
        type: IngredientTypes.main,
        name: "Биокотлета из марсианской Магнолии",
        proteins: 420,
        fat: 142,
        carbohydrates: 242,
        calories: 4242,
        price: 424,
        image: "https://code.s3.yandex.net/react/code/meat-01.png",
        image_large: "https://code.s3.yandex.net/react/code/meat-01-large.png",
    },
    {
        _id: "643d69a5c3f7b9001cfa093e",
        type: IngredientTypes.main,
        name: "Филе Люминесцентного тетраодонтимформа",
        proteins: 44,
        fat: 26,
        carbohydrates: 85,
        calories: 643,
        price: 988,
        image: "https://code.s3.yandex.net/react/code/meat-03.png",
        image_large: "https://code.s3.yandex.net/react/code/meat-03-large.png",
    },
    {
        _id: "643d69a5c3f7b9001cfa093f",
        type: IngredientTypes.main,
        name: "Мясо бессмертных моллюсков Protostomia",
        proteins: 433,
        fat: 244,
        carbohydrates: 33,
        calories: 420,
        price: 1337,
        image: "https://code.s3.yandex.net/react/code/meat-02.png",
        image_large: "https://code.s3.yandex.net/react/code/meat-02-large.png",
    },
    {
        _id: "643d69a5c3f7b9001cfa0940",
        type: IngredientTypes.main,
        name: "Говяжий метеорит (отбивная)",
        proteins: 800,
        fat: 800,
        carbohydrates: 300,
        calories: 2674,
        price: 3000,
        image: "https://code.s3.yandex.net/react/code/meat-04.png",
        image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
    },
    {
        _id: "643d69a5c3f7b9001cfa0946",
        type: IngredientTypes.main,
        name: "Хрустящие минеральные кольца",
        proteins: 808,
        fat: 689,
        carbohydrates: 609,
        calories: 986,
        price: 300,
        image: "https://code.s3.yandex.net/react/code/mineral_rings.png",
        image_large: "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
    }, {
        _id: "643d69a5c3f7b9001cfa0947",
        type: IngredientTypes.main,
        name: "Плоды Фалленианского дерева",
        proteins: 20,
        fat: 5,
        carbohydrates: 55,
        calories: 77,
        price: 874,
        image: "https://code.s3.yandex.net/react/code/sp_1.png",
        image_large: "https://code.s3.yandex.net/react/code/sp_1-large.png",
    }, {
        _id: "643d69a5c3f7b9001cfa0948",
        type: IngredientTypes.main,
        name: "Кристаллы марсианских альфа-сахаридов",
        proteins: 234,
        fat: 432,
        carbohydrates: 111,
        calories: 189,
        price: 762,
        image: "https://code.s3.yandex.net/react/code/core.png",
        image_large: "https://code.s3.yandex.net/react/code/core-large.png",
    }, {
        _id: "643d69a5c3f7b9001cfa0949",
        type: IngredientTypes.main,
        name: "Мини-салат Экзо-Плантаго",
        proteins: 1,
        fat: 2,
        carbohydrates: 3,
        calories: 6,
        price: 4400,
        image: "https://code.s3.yandex.net/react/code/salad.png",
        image_large: "https://code.s3.yandex.net/react/code/salad-large.png",
    }, {
        _id: "643d69a5c3f7b9001cfa094a",
        type: IngredientTypes.main,
        name: "Сыр с астероидной плесенью",
        proteins: 84,
        fat: 48,
        carbohydrates: 420,
        calories: 3377,
        price: 4142,
        image: "https://code.s3.yandex.net/react/code/cheese.png",
        image_large: "https://code.s3.yandex.net/react/code/cheese-large.png",
    },
    {
        _id: "643d69a5c3f7b9001cfa0944",
        type: IngredientTypes.sauce,
        name: "Соус традиционный галактический",
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: "https://code.s3.yandex.net/react/code/sauce-03.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-03-large.png",
    },
    {
        _id: "643d69a5c3f7b9001cfa0945",
        type: IngredientTypes.sauce,
        name: "Соус с шипами Антарианского плоскоходца",
        proteins: 101,
        fat: 99,
        carbohydrates: 100,
        calories: 100,
        price: 88,
        image: "https://code.s3.yandex.net/react/code/sauce-01.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-01-large.png",
    },
    {
        _id: "643d69a5c3f7b9001cfa0942",
        type: IngredientTypes.sauce,
        name: "Соус Spicy-X",
        proteins: 30,
        fat: 20,
        carbohydrates: 40,
        calories: 30,
        price: 90,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
    },
    {
        _id: "643d69a5c3f7b9001cfa0943",
        type: IngredientTypes.sauce,
        name: "Соус фирменный Space Sauce",
        proteins: 50,
        fat: 22,
        carbohydrates: 11,
        calories: 14,
        price: 80,
        image: "https://code.s3.yandex.net/react/code/sauce-04.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
    },
];

export const INGREDIENT1 = TEST_INGREDIENTS[0];
export const INGREDIENT2 = TEST_INGREDIENTS[1];
export const INGREDIENT3 = TEST_INGREDIENTS[2];
